/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolicitacaoCancelamentoRouteImport } from './routes/solicitacao-cancelamento'
import { Route as RenovacaoSicafRouteImport } from './routes/renovacao-sicaf'
import { Route as ProcedimentosCadbrasilRouteImport } from './routes/procedimentos-cadbrasil'
import { Route as ProcedimentoLoginSenhaRouteImport } from './routes/procedimento-login-senha'
import { Route as InstaladorAssistenteCadbrasilRouteImport } from './routes/instalador-assistente-cadbrasil'
import { Route as EmpresaInaptaSicafRouteImport } from './routes/empresa-inapta-sicaf'
import { Route as CredenciamentoSicafRouteImport } from './routes/credenciamento-sicaf'
import { Route as CredenciamentoRouteImport } from './routes/credenciamento'
import { Route as ConclusaoCancelamentoRouteImport } from './routes/conclusao-cancelamento'
import { Route as ConclusaoCadastroRouteImport } from './routes/conclusao-cadastro'
import { Route as CadastroSicafPessoaJuridicaRouteImport } from './routes/cadastro-sicaf-pessoa-juridica'
import { Route as CadastroSicafMeiRouteImport } from './routes/cadastro-sicaf-mei'
import { Route as AssistenteAjudaRouteImport } from './routes/assistente-ajuda'
import { Route as AssistenteRouteImport } from './routes/assistente'
import { Route as IndexRouteImport } from './routes/index'

const SolicitacaoCancelamentoRoute = SolicitacaoCancelamentoRouteImport.update({
  id: '/solicitacao-cancelamento',
  path: '/solicitacao-cancelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RenovacaoSicafRoute = RenovacaoSicafRouteImport.update({
  id: '/renovacao-sicaf',
  path: '/renovacao-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentosCadbrasilRoute = ProcedimentosCadbrasilRouteImport.update({
  id: '/procedimentos-cadbrasil',
  path: '/procedimentos-cadbrasil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcedimentoLoginSenhaRoute = ProcedimentoLoginSenhaRouteImport.update({
  id: '/procedimento-login-senha',
  path: '/procedimento-login-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const InstaladorAssistenteCadbrasilRoute =
  InstaladorAssistenteCadbrasilRouteImport.update({
    id: '/instalador-assistente-cadbrasil',
    path: '/instalador-assistente-cadbrasil',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmpresaInaptaSicafRoute = EmpresaInaptaSicafRouteImport.update({
  id: '/empresa-inapta-sicaf',
  path: '/empresa-inapta-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const CredenciamentoSicafRoute = CredenciamentoSicafRouteImport.update({
  id: '/credenciamento-sicaf',
  path: '/credenciamento-sicaf',
  getParentRoute: () => rootRouteImport,
} as any)
const CredenciamentoRoute = CredenciamentoRouteImport.update({
  id: '/credenciamento',
  path: '/credenciamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusaoCancelamentoRoute = ConclusaoCancelamentoRouteImport.update({
  id: '/conclusao-cancelamento',
  path: '/conclusao-cancelamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusaoCadastroRoute = ConclusaoCadastroRouteImport.update({
  id: '/conclusao-cadastro',
  path: '/conclusao-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroSicafPessoaJuridicaRoute =
  CadastroSicafPessoaJuridicaRouteImport.update({
    id: '/cadastro-sicaf-pessoa-juridica',
    path: '/cadastro-sicaf-pessoa-juridica',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastroSicafMeiRoute = CadastroSicafMeiRouteImport.update({
  id: '/cadastro-sicaf-mei',
  path: '/cadastro-sicaf-mei',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteAjudaRoute = AssistenteAjudaRouteImport.update({
  id: '/assistente-ajuda',
  path: '/assistente-ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistenteRoute = AssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/assistente-ajuda': typeof AssistenteAjudaRoute
  '/cadastro-sicaf-mei': typeof CadastroSicafMeiRoute
  '/cadastro-sicaf-pessoa-juridica': typeof CadastroSicafPessoaJuridicaRoute
  '/conclusao-cadastro': typeof ConclusaoCadastroRoute
  '/conclusao-cancelamento': typeof ConclusaoCancelamentoRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/credenciamento-sicaf': typeof CredenciamentoSicafRoute
  '/empresa-inapta-sicaf': typeof EmpresaInaptaSicafRoute
  '/instalador-assistente-cadbrasil': typeof InstaladorAssistenteCadbrasilRoute
  '/procedimento-login-senha': typeof ProcedimentoLoginSenhaRoute
  '/procedimentos-cadbrasil': typeof ProcedimentosCadbrasilRoute
  '/renovacao-sicaf': typeof RenovacaoSicafRoute
  '/solicitacao-cancelamento': typeof SolicitacaoCancelamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/assistente-ajuda': typeof AssistenteAjudaRoute
  '/cadastro-sicaf-mei': typeof CadastroSicafMeiRoute
  '/cadastro-sicaf-pessoa-juridica': typeof CadastroSicafPessoaJuridicaRoute
  '/conclusao-cadastro': typeof ConclusaoCadastroRoute
  '/conclusao-cancelamento': typeof ConclusaoCancelamentoRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/credenciamento-sicaf': typeof CredenciamentoSicafRoute
  '/empresa-inapta-sicaf': typeof EmpresaInaptaSicafRoute
  '/instalador-assistente-cadbrasil': typeof InstaladorAssistenteCadbrasilRoute
  '/procedimento-login-senha': typeof ProcedimentoLoginSenhaRoute
  '/procedimentos-cadbrasil': typeof ProcedimentosCadbrasilRoute
  '/renovacao-sicaf': typeof RenovacaoSicafRoute
  '/solicitacao-cancelamento': typeof SolicitacaoCancelamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistente': typeof AssistenteRoute
  '/assistente-ajuda': typeof AssistenteAjudaRoute
  '/cadastro-sicaf-mei': typeof CadastroSicafMeiRoute
  '/cadastro-sicaf-pessoa-juridica': typeof CadastroSicafPessoaJuridicaRoute
  '/conclusao-cadastro': typeof ConclusaoCadastroRoute
  '/conclusao-cancelamento': typeof ConclusaoCancelamentoRoute
  '/credenciamento': typeof CredenciamentoRoute
  '/credenciamento-sicaf': typeof CredenciamentoSicafRoute
  '/empresa-inapta-sicaf': typeof EmpresaInaptaSicafRoute
  '/instalador-assistente-cadbrasil': typeof InstaladorAssistenteCadbrasilRoute
  '/procedimento-login-senha': typeof ProcedimentoLoginSenhaRoute
  '/procedimentos-cadbrasil': typeof ProcedimentosCadbrasilRoute
  '/renovacao-sicaf': typeof RenovacaoSicafRoute
  '/solicitacao-cancelamento': typeof SolicitacaoCancelamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistente'
    | '/assistente-ajuda'
    | '/cadastro-sicaf-mei'
    | '/cadastro-sicaf-pessoa-juridica'
    | '/conclusao-cadastro'
    | '/conclusao-cancelamento'
    | '/credenciamento'
    | '/credenciamento-sicaf'
    | '/empresa-inapta-sicaf'
    | '/instalador-assistente-cadbrasil'
    | '/procedimento-login-senha'
    | '/procedimentos-cadbrasil'
    | '/renovacao-sicaf'
    | '/solicitacao-cancelamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistente'
    | '/assistente-ajuda'
    | '/cadastro-sicaf-mei'
    | '/cadastro-sicaf-pessoa-juridica'
    | '/conclusao-cadastro'
    | '/conclusao-cancelamento'
    | '/credenciamento'
    | '/credenciamento-sicaf'
    | '/empresa-inapta-sicaf'
    | '/instalador-assistente-cadbrasil'
    | '/procedimento-login-senha'
    | '/procedimentos-cadbrasil'
    | '/renovacao-sicaf'
    | '/solicitacao-cancelamento'
  id:
    | '__root__'
    | '/'
    | '/assistente'
    | '/assistente-ajuda'
    | '/cadastro-sicaf-mei'
    | '/cadastro-sicaf-pessoa-juridica'
    | '/conclusao-cadastro'
    | '/conclusao-cancelamento'
    | '/credenciamento'
    | '/credenciamento-sicaf'
    | '/empresa-inapta-sicaf'
    | '/instalador-assistente-cadbrasil'
    | '/procedimento-login-senha'
    | '/procedimentos-cadbrasil'
    | '/renovacao-sicaf'
    | '/solicitacao-cancelamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistenteRoute: typeof AssistenteRoute
  AssistenteAjudaRoute: typeof AssistenteAjudaRoute
  CadastroSicafMeiRoute: typeof CadastroSicafMeiRoute
  CadastroSicafPessoaJuridicaRoute: typeof CadastroSicafPessoaJuridicaRoute
  ConclusaoCadastroRoute: typeof ConclusaoCadastroRoute
  ConclusaoCancelamentoRoute: typeof ConclusaoCancelamentoRoute
  CredenciamentoRoute: typeof CredenciamentoRoute
  CredenciamentoSicafRoute: typeof CredenciamentoSicafRoute
  EmpresaInaptaSicafRoute: typeof EmpresaInaptaSicafRoute
  InstaladorAssistenteCadbrasilRoute: typeof InstaladorAssistenteCadbrasilRoute
  ProcedimentoLoginSenhaRoute: typeof ProcedimentoLoginSenhaRoute
  ProcedimentosCadbrasilRoute: typeof ProcedimentosCadbrasilRoute
  RenovacaoSicafRoute: typeof RenovacaoSicafRoute
  SolicitacaoCancelamentoRoute: typeof SolicitacaoCancelamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solicitacao-cancelamento': {
      id: '/solicitacao-cancelamento'
      path: '/solicitacao-cancelamento'
      fullPath: '/solicitacao-cancelamento'
      preLoaderRoute: typeof SolicitacaoCancelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renovacao-sicaf': {
      id: '/renovacao-sicaf'
      path: '/renovacao-sicaf'
      fullPath: '/renovacao-sicaf'
      preLoaderRoute: typeof RenovacaoSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimentos-cadbrasil': {
      id: '/procedimentos-cadbrasil'
      path: '/procedimentos-cadbrasil'
      fullPath: '/procedimentos-cadbrasil'
      preLoaderRoute: typeof ProcedimentosCadbrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedimento-login-senha': {
      id: '/procedimento-login-senha'
      path: '/procedimento-login-senha'
      fullPath: '/procedimento-login-senha'
      preLoaderRoute: typeof ProcedimentoLoginSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalador-assistente-cadbrasil': {
      id: '/instalador-assistente-cadbrasil'
      path: '/instalador-assistente-cadbrasil'
      fullPath: '/instalador-assistente-cadbrasil'
      preLoaderRoute: typeof InstaladorAssistenteCadbrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa-inapta-sicaf': {
      id: '/empresa-inapta-sicaf'
      path: '/empresa-inapta-sicaf'
      fullPath: '/empresa-inapta-sicaf'
      preLoaderRoute: typeof EmpresaInaptaSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credenciamento-sicaf': {
      id: '/credenciamento-sicaf'
      path: '/credenciamento-sicaf'
      fullPath: '/credenciamento-sicaf'
      preLoaderRoute: typeof CredenciamentoSicafRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credenciamento': {
      id: '/credenciamento'
      path: '/credenciamento'
      fullPath: '/credenciamento'
      preLoaderRoute: typeof CredenciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusao-cancelamento': {
      id: '/conclusao-cancelamento'
      path: '/conclusao-cancelamento'
      fullPath: '/conclusao-cancelamento'
      preLoaderRoute: typeof ConclusaoCancelamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusao-cadastro': {
      id: '/conclusao-cadastro'
      path: '/conclusao-cadastro'
      fullPath: '/conclusao-cadastro'
      preLoaderRoute: typeof ConclusaoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-sicaf-pessoa-juridica': {
      id: '/cadastro-sicaf-pessoa-juridica'
      path: '/cadastro-sicaf-pessoa-juridica'
      fullPath: '/cadastro-sicaf-pessoa-juridica'
      preLoaderRoute: typeof CadastroSicafPessoaJuridicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-sicaf-mei': {
      id: '/cadastro-sicaf-mei'
      path: '/cadastro-sicaf-mei'
      fullPath: '/cadastro-sicaf-mei'
      preLoaderRoute: typeof CadastroSicafMeiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente-ajuda': {
      id: '/assistente-ajuda'
      path: '/assistente-ajuda'
      fullPath: '/assistente-ajuda'
      preLoaderRoute: typeof AssistenteAjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistente': {
      id: '/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AssistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistenteRoute: AssistenteRoute,
  AssistenteAjudaRoute: AssistenteAjudaRoute,
  CadastroSicafMeiRoute: CadastroSicafMeiRoute,
  CadastroSicafPessoaJuridicaRoute: CadastroSicafPessoaJuridicaRoute,
  ConclusaoCadastroRoute: ConclusaoCadastroRoute,
  ConclusaoCancelamentoRoute: ConclusaoCancelamentoRoute,
  CredenciamentoRoute: CredenciamentoRoute,
  CredenciamentoSicafRoute: CredenciamentoSicafRoute,
  EmpresaInaptaSicafRoute: EmpresaInaptaSicafRoute,
  InstaladorAssistenteCadbrasilRoute: InstaladorAssistenteCadbrasilRoute,
  ProcedimentoLoginSenhaRoute: ProcedimentoLoginSenhaRoute,
  ProcedimentosCadbrasilRoute: ProcedimentosCadbrasilRoute,
  RenovacaoSicafRoute: RenovacaoSicafRoute,
  SolicitacaoCancelamentoRoute: SolicitacaoCancelamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
